// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVRTaZdvs0fhZJdhzds09CoI5c1fXAVu0',
    appId: '1:281107973236:web:20bf684a8e660f752f3d21',
    messagingSenderId: '281107973236',
    projectId: 'sonho-saudavel',
    authDomain: 'sonho-saudavel.firebaseapp.com',
    storageBucket: 'sonho-saudavel.firebasestorage.app',
    measurementId: 'G-QGTTX1PVTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyXpOFs5M0xWDD8ujs7DNnB8tsywoEk0Q',
    appId: '1:281107973236:android:6b549e11839539d22f3d21',
    messagingSenderId: '281107973236',
    projectId: 'sonho-saudavel',
    storageBucket: 'sonho-saudavel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7MV3aVq7ffnLUT3dXF8K1HwjfZ86QP3M',
    appId: '1:281107973236:ios:832bcd625d762b162f3d21',
    messagingSenderId: '281107973236',
    projectId: 'sonho-saudavel',
    storageBucket: 'sonho-saudavel.firebasestorage.app',
    iosBundleId: 'com.example.sonhoSaudavelTeste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7MV3aVq7ffnLUT3dXF8K1HwjfZ86QP3M',
    appId: '1:281107973236:ios:832bcd625d762b162f3d21',
    messagingSenderId: '281107973236',
    projectId: 'sonho-saudavel',
    storageBucket: 'sonho-saudavel.firebasestorage.app',
    iosBundleId: 'com.example.sonhoSaudavelTeste',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVRTaZdvs0fhZJdhzds09CoI5c1fXAVu0',
    appId: '1:281107973236:web:26cc6b10daff5cca2f3d21',
    messagingSenderId: '281107973236',
    projectId: 'sonho-saudavel',
    authDomain: 'sonho-saudavel.firebaseapp.com',
    storageBucket: 'sonho-saudavel.firebasestorage.app',
    measurementId: 'G-RSB3D5SY7X',
  );
}
